name: CI

# Menjalankan secara otomatis setiap 4 jam
on:
  schedule:
    - cron: '0 */4 * * *'  # Setiap 4 jam pada menit ke-0
  workflow_dispatch:

jobs:
  update-repo:
    runs-on: ubuntu-latest  # Menjalankan job di lingkungan Ubuntu
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Script
        run: |
          echo "" > README.md
          git config user.name "ahmadzidni2"
          git config user.email "zdngaminglive@gmail.com"
          git add README.md
          git commit -m "Test"
          git push
