name: CI

# Menjalankan secara otomatis setiap 4 jam
on:
  schedule:
    - cron: '*/1 * * * *' # Setiap 4 jam pada menit ke-0

jobs:
  update-repo:
    runs-on: ubuntu-latest  # Menjalankan job di lingkungan Ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Mengambil kode dari repository

      - name: Update README with timestamp in WIB
        run: |
          export TZ="Asia/Jakarta"  # Mengatur zona waktu ke Asia/Jakarta (WIB)
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S %Z")  # Mendapatkan timestamp dalam format yang diinginkan (WIB)
          echo "Last updated: $TIMESTAMP" > README.md  # Perbarui atau buat README.md dengan timestamp WIB

      - name: Configure Git
        run: |
          git config user.name "ahmadzidni2"  # Mengatur nama pengguna untuk commit
          git config user.email "zdngaminglive@gmail.com"  # Mengatur email pengguna untuk commit

      - name: Commit changes
        run: |
          git add README.md  # Menambahkan README.md ke staging area
          git commit -S -m "Auto update README at $TIMESTAMP" || echo "No changes to commit"  # Commit dengan tanda tangan jika ada perubahan

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Gunakan token yang aman untuk melakukan push
        run: |
          git push origin main  # Mengirimkan perubahan ke branch 'main'
